### ISSUE TITLE
Example of a letter for creating/editing a ticket

### ISSUE THREAD

**Issue by Shpil93** [jbostoen/itop-jb-mail-to-ticket-automation-v2#12]
Can i get example of a letter for creating/editing a ticket. I don't understand what format it is necessary to send letters to create a ticket. Thanks.

**Comment by jbostoen** [comment]
Can you be more specific please? What do you mean by "letter"? An e-mail? Any e-mail will do to create ticket.

If an e-mail needs to be linked to a specific ticket, by default it needs a certain pattern such as R-123456 in the subject title (can be configured to be something else).

A lot of the info from https://www.itophub.io/wiki/page?id=extensions%3Aticket-from-email still applies.

**Comment by Shpil93** [comment]
If I understand correctly, when I send mail to email, a ticket should be created. What email format is required to create a ticket?

**Comment by jbostoen** [comment]
There's no specific format required at all.

**Comment by Shpil93** [comment]
I configured to receive mail to imap in itop, but the ticket is not created

**Comment by Shpil93** [comment]
What information should be included in the email to create a ticket?

**Comment by Shpil93** [comment]
![image](https://user-images.githubusercontent.com/51797211/150091481-ba44ba21-1432-4a17-9409-0540a04e9ad7.png)

How did they do it?

**Comment by jbostoen** [comment]
Please use the "edit" button instead instead of creating consecutive comments.

Do you see mailbox content?
If not, you will need to verify and share your settings (exclude sensitive information).

**Comment by Shpil93** [comment]
![2022-01-19_11-30](https://user-images.githubusercontent.com/51797211/150093915-32d1aad1-607f-4317-a9d1-f1563f59f7c6.png)

**Comment by jbostoen** [comment]
Better ask at Combodo's forums, you're clearly not using my fork ;)

**Comment by Shpil93** [comment]
Can you show me an example of your settings?

**Comment by jbostoen** [comment]
Closed - if using Combodo's version, please ask the question on iTop's community forums.
