### ISSUE TITLE
Question about your extension

### ISSUE THREAD

**Issue by jothoma1** [jbostoen/itop-jb-mail-to-ticket-automation-v2#28]
Hello,
first thanks for your work with itop. I'm using it for lots of my work mainly for the CMDB feature but also for ticketing.

I would like to test your extension on my new job. My team is using email for requests and incidents. I would like to test adding this extension to fill our itop and be more efficient.
Is it possible to add email from an on premise Microsoft exchange server ?
If contacts do not exists on itop can we create tickets but based on a generic user ?
Thanks again

**Comment by jbostoen** [comment]
Yes, you can still use an on premises MS Exchange Server. That's how I originally started out myself before moving to MS Office 365.

Mind that tickets are always linked to contacts, you just specify the default values that should be used for an unknown contact. See documentation.
