### ISSUE TITLE
How to install this extension

### ISSUE THREAD

**Issue by bezgali** [jbostoen/itop-jb-mail-to-ticket-automation-v2#9]
hello,

I did not understand how to put your code in itop
Could you please explain it ?

**Comment by jbostoen** [comment]
Download the code from "releases". All files should be in a folder under <iTop dir>/extensions/jb-mail-to-ticket-automation-v2

Further: follow the instructions on the iTop Hub on how to manually install an extension.

**Comment by bezgali** [comment]
thank you!
